### GENERAL SETTINGS ###

# Site settings
title: ASSET
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/ASSET" #important: start with /
url: "http://www.scorelab.org/ASSET"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#3B78AF" #"#F70031"
  primary_rgb: "59,120,175" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/SCoRe.UCSC/
  - title: twitter
    url: https://twitter.com/scoreucsc

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Some Ave, 987,
    - 23890, New York,
    - United States.
email: hello@solidtheme.com
tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Dr. Kasun de Zoysa
    position: Senior Lecturer, UCSC
    text: BSc(Col), PhLic(Stockholm), PhD(Stockholm)(Senior Lecturer Gr. II)
    img: kasun.jpg
    social:
      - title: envelope #use for email address
        url: mailto:kasun@ucsc.lk
  - name: Dr. Chamath Keppitiyagama
    position: Senior Lecturer, UCSC
    text: BSc(Col), MSc(British Columbia), PhD (British Columbia)(Senior Lecturer Gr. I)
    img: chamath.jpg
    social:
      - title: envelope #use for email address
        url: mailto:chamath@ucsc.lk

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO
